import { useEffect, useState, type FormEvent } from 'react'
import { Link } from 'react-router-dom'
import { useCurrentUser } from '../lib/store'
import type { User, Progress } from '../lib/model'
import type { Payment, LedgerEntry, AuditEntry } from '../../server/database'

type Data={users:{user:User;progress:Progress;activeSessions:number}[];payments:Payment[];ledger:LedgerEntry[];audit:AuditEntry[]}
const money=(n:number)=>(n/100).toLocaleString('fr-FR',{style:'currency',currency:'EUR'})
const euro=(v:FormDataEntryValue|null)=>Math.round(Number(v)*100)
const labels:Record<string,string>={pending:'À vérifier',paid:'Payé',refunded:'Remboursé',cancelled:'Annulé',income:'Recette',refund:'Remboursement',expense:'Dépense'}
function exportCsv(name:string, rows:unknown[][]){
 const csv='\ufeff'+rows.map(row=>row.map(v=>'"'+String(v??'').replace(/^[=+@\-\t\r]/,"'$&").replace(/"/g,'""')+'"').join(';')).join('\r\n')
 const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)
}
export default function Admin(){
 const user=useCurrentUser(),[data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[tab,setTab]=useState('users'),[search,setSearch]=useState(''),[selected,setSelected]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState('')
 async function request(body?:Record<string,unknown>){
  setBusy(true);setError('');setMessage('')
  try{const r=await fetch('/api/account?view=admin',{method:body?'POST':'GET',credentials:'same-origin',cache:'no-store',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify({...body,operationId:crypto.randomUUID()}):undefined});const d=await r.json();if(!r.ok)throw Error(d.error);setData(d);if(body)setMessage('Modification enregistrée.');return true}catch(e){setError((e as Error).message);return false}finally{setBusy(false)}
 }
 useEffect(()=>{if(user?.role==='admin')void request()},[user?.id])
 if(user?.role!=='admin')return <div className="container page"><h1>Administration</h1><p>Connecte-toi avec le compte administrateur autorisé.</p><Link className="btn" to="/connexion?next=/admin">Connexion administrateur</Link></div>
 if(!data)return <div className="container page"><h1>Administration</h1><p role="status">{error||'Chargement…'}</p>{error&&<button className="btn" onClick={()=>void request()}>Réessayer</button>}</div>
 const active=data.users.find(x=>x.user.id===selected)
 const within=(date:string)=>(!from||date.slice(0,10)>=from)&&(!to||date.slice(0,10)<=to)
 const ledger=data.ledger.filter(x=>within(x.date)),income=ledger.filter(x=>x.kind==='income').reduce((n,x)=>n+x.amount,0),refund=ledger.filter(x=>x.kind==='refund').reduce((n,x)=>n+x.amount,0),fees=ledger.reduce((n,x)=>n+x.fee,0),expense=ledger.filter(x=>x.kind==='expense').reduce((n,x)=>n+x.amount,0)
 const users=data.users.filter(x=>`${x.user.displayName} ${x.user.email} ${x.user.username}`.toLowerCase().includes(search.toLowerCase()))
 const name=(id:string)=>data.users.find(x=>x.user.id===id)?.user.displayName??'Compte clôturé'
 const bookings=data.users.flatMap(x=>x.progress.bookings.map(b=>({...b,userId:x.user.id,name:x.user.displayName}))).sort((a,b)=>(b.date+b.time).localeCompare(a.date+a.time))
 function submit(e:FormEvent<HTMLFormElement>,action:string,id?:string){e.preventDefault();const f=new FormData(e.currentTarget);void request({action,id,...Object.fromEntries(f),...(action==='adminExpense'||action==='adminRefund'?{amount:euro(f.get('amount'))}:{}),...(action==='adminPayment'?{fee:euro(f.get('fee'))}:{})})}
 return <div className="container page admin-page"><div className="row between"><div><p className="eyebrow">TALK TO ME CLUB</p><h1>Administration</h1><p className="muted">{user.email} · Paiements PayPal validés manuellement</p></div><button className="btn ghost" disabled={busy} onClick={()=>void request()}>Actualiser</button></div>
  <div className="admin-summary"><div className="card"><strong>{data.users.filter(x=>!x.user.archived).length}</strong><span>Profils actifs</span></div><div className="card"><strong>{bookings.filter(x=>x.status==='demandée').length}</strong><span>Demandes de cours</span></div><div className="card"><strong>{data.payments.filter(x=>x.status==='pending').length}</strong><span>Paiements à vérifier</span></div></div>
  <nav className="admin-tabs" aria-label="Rubriques administrateur">{[['users','Utilisateurs'],['bookings','Réservations'],['payments','Paiements PayPal'],['ledger','Comptabilité'],['audit','Historique']].map(([id,label])=><button key={id} className={`btn ${tab===id?'':'ghost'}`} onClick={()=>setTab(id)}>{label}</button>)}</nav>
  {error&&<p role="alert" className="error">{error}</p>}{message&&<p role="status" className="notice">{message}</p>}
  <fieldset className="admin-body" disabled={busy}>
  {tab==='users'&&<><div className="row"><input className="input" aria-label="Chercher un utilisateur" placeholder="Nom, e-mail ou pseudo…" value={search} onChange={e=>setSearch(e.target.value)}/><button className="btn ghost" onClick={()=>exportCsv('utilisateurs.csv',[['Nom','E-mail','Pseudo','Inscription','Suspendu','Archivé','Illimité','Crédits','XP','Leçons terminées'],...users.map(x=>[x.user.displayName,x.user.email,x.user.username,x.user.createdAt,x.user.suspended??false,x.user.archived??false,x.user.isDemo??false,x.progress.packCredits,x.progress.xp,Object.values(x.progress.lessons).filter(l=>l.completed).length])])}>Exporter CSV</button></div>
   <details className="card mt"><summary>Créer un utilisateur</summary><form className="admin-form" onSubmit={e=>submit(e,'adminCreate')}><label>Nom<input name="displayName" className="input" required maxLength={40}/></label><label>E-mail<input name="email" type="email" className="input" required/></label><label>Pseudo<input name="username" className="input" pattern="[a-z0-9._]{3,20}" required/></label><label>Mot de passe temporaire<input name="password" type="password" className="input" minLength={12} required autoComplete="new-password"/></label><button className="btn">Créer le profil</button></form></details>
   <div className="admin-user-layout mt"><div className="stack">{users.map(x=><button key={x.user.id} className={`card admin-user ${selected===x.user.id?'selected':''}`} onClick={()=>setSelected(x.user.id)}><strong>{x.user.displayName}</strong><span>{x.user.email}</span><small>{x.user.role==='admin'?'Administrateur':x.user.archived?'Archivé':x.user.suspended?'Suspendu':x.user.isDemo?'Accès illimité':'Élève'} · {x.progress.xp} XP</small></button>)}{!users.length&&<p>Aucun utilisateur trouvé.</p>}</div>
   {active?<section className="card" key={selected}><h2>{active.user.displayName}</h2><p className="small muted">Inscrit le {new Date(active.user.createdAt).toLocaleDateString('fr-FR')} · {active.activeSessions} session(s) active(s)</p><p>{Object.values(active.progress.lessons).filter(l=>l.completed).length} leçons terminées · {active.progress.practice?.length??0} activités orales et jeux</p>
   {active.user.role==='admin'?<p>Compte administrateur protégé. Modifie ton mot de passe depuis <Link to="/profil/modifier">ton profil</Link>.</p>:<><form className="admin-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void request({action:'adminUser',id:selected,patch:{displayName:f.get('displayName'),email:f.get('email'),username:f.get('username'),packCredits:Number(f.get('credits')),isDemo:f.has('unlimited'),suspended:f.has('suspended')}})}}><label>Nom<input name="displayName" className="input" defaultValue={active.user.displayName} required/></label><label>E-mail<input name="email" type="email" className="input" defaultValue={active.user.email} required/></label><label>Pseudo<input name="username" className="input" defaultValue={active.user.username} required/></label><label>Crédit d’heures<input name="credits" type="number" min="0" max="10000" className="input" defaultValue={active.progress.packCredits} required/></label><label><input type="checkbox" name="unlimited" defaultChecked={active.user.isDemo}/> Accès illimité</label><label><input type="checkbox" name="suspended" defaultChecked={active.user.suspended}/> Suspendre la connexion</label><button className="btn">Enregistrer le profil</button></form>
   <details className="mt"><summary>Sécurité et gestion du compte</summary><div className="stack mt"><button className="btn ghost" onClick={()=>void request({action:'adminRevoke',id:selected})}>Déconnecter tous les appareils</button><button className="btn ghost" onClick={()=>{if(confirm('Effacer la progression pédagogique de ce profil ? Les paiements et réservations seront conservés.'))void request({action:'adminReset',id:selected})}}>Réinitialiser la progression</button><button className="btn ghost" onClick={()=>{if(confirm(active.user.archived?'Restaurer le profil ?':'Archiver ce profil et couper ses sessions ? Les écritures comptables seront conservées.'))void request({action:active.user.archived?'adminRestore':'adminArchive',id:selected})}}>{active.user.archived?'Restaurer':'Archiver'} le profil</button><form className="admin-form" onSubmit={e=>{if(!confirm('Remplacer le mot de passe et déconnecter tous les appareils ?')){e.preventDefault();return}submit(e,'adminPassword',selected)}}><label>Nouveau mot de passe temporaire<input className="input" name="password" type="password" minLength={12} autoComplete="new-password" required/></label><button className="btn ghost">Remplacer le mot de passe</button></form></div></details></>}
   <details className="mt"><summary>Résultats pédagogiques ({active.progress.history.length})</summary>{active.progress.history.slice(0,50).map(h=><p key={h.id}>{h.title} · {h.score}/{h.total} · {new Date(h.date).toLocaleDateString('fr-FR')}</p>)}</details></section>:<div className="card"><p>Sélectionne un profil pour gérer ses informations et ses accès.</p></div>}</div></>}
  {tab==='bookings'&&<div className="stack">{!bookings.length&&<p>Aucune réservation.</p>}{bookings.map(b=><article className="card" key={b.id}><h2>{b.name} · {b.date} à {b.time}</h2><p>Heure de Paris · {b.topic} · {b.formula==='single'?'1 heure':b.usedCredit?'Crédit':'Pack / accès illimité'}</p><p>{b.message}</p><p>Statut : {b.status} · Paiement : {b.paymentId?labels[data.payments.find(p=>p.id===b.paymentId)?.status??'pending']:'Crédit ou accès illimité'}</p><div className="row"><button className="btn" disabled={b.status==='annulée'||b.status==='confirmée'} onClick={()=>void request({action:'adminBooking',id:b.id,status:'confirmée'})}>Confirmer le créneau</button><button className="btn ghost" disabled={b.status==='annulée'} onClick={()=>{if(confirm('Annuler ce cours ? Un crédit utilisé sera restitué. Un paiement PayPal doit être remboursé séparément.'))void request({action:'adminBooking',id:b.id,status:'annulée'})}}>Annuler</button></div></article>)}</div>}
  {tab==='payments'&&<><div className="card"><h2>Rapprochement PayPal</h2><p>Vérifie le destinataire Siasiakorea, le montant reçu en EUR et la référence dans ton compte PayPal avant de valider. Une validation de pack active les 9 heures restantes. Aucun paiement n’est confirmé par le simple clic de l’élève.</p><a className="btn ghost" href="https://www.paypal.com/myaccount/activities/" target="_blank" rel="noreferrer">Ouvrir mon activité PayPal</a></div><div className="stack mt">{!data.payments.length&&<p>Aucun règlement à rapprocher.</p>}{[...data.payments].reverse().map(p=><article className="card" key={p.id}><h2>{p.customer} · {money(p.amount)}</h2><p>{labels[p.status]} · {new Date(p.createdAt).toLocaleDateString('fr-FR')} · EUR</p><p className="small">Référence de réservation : {p.bookingId}</p>{p.reference&&<p>PayPal : {p.reference} · Frais : {money(p.fee??0)} · Remboursé : {money(p.refunded??0)}</p>}{p.status==='pending'&&<form className="admin-form" onSubmit={e=>{if(!confirm('As-tu vérifié que ce règlement est réellement reçu sur PayPal, pour ce montant en EUR ?')){e.preventDefault();return}submit(e,'adminPayment',p.id)}}><label>Identifiant de transaction PayPal<input className="input" name="reference" minLength={6} required/></label><label>Frais PayPal réels (€)<input className="input" type="number" name="fee" min="0" step="0.01" max={p.amount/100} defaultValue="0" required/></label><button className="btn">Valider le paiement reçu</button></form>}{p.status==='paid'&&<details><summary>Enregistrer un remboursement déjà effectué</summary><p>Effectue d’abord le remboursement dans PayPal. Cette saisie ajoute une écriture comptable ; elle ne transfère pas d’argent. Ajuste aussi les crédits dans le profil si nécessaire.</p><form className="admin-form" onSubmit={e=>submit(e,'adminRefund',p.id)}><label>Montant (€)<input className="input" name="amount" type="number" min="0.01" max={(p.amount-(p.refunded??0))/100} step="0.01" required/></label><label>Référence PayPal du remboursement<input className="input" name="reference" minLength={6} required/></label><label>Motif<input className="input" name="label" required/></label><button className="btn ghost">Enregistrer le remboursement</button></form></details>}</article>)}</div></>}
  {tab==='ledger'&&<><div className="card"><h2>Registre des encaissements et dépenses</h2><p className="muted">Montants en EUR. Ce registre couvre les opérations saisies ici ; il n’importe pas l’historique PayPal. Le solde ci-dessous n’est pas le solde bancaire. Aucun calcul de TVA ni déclaration fiscale automatique.</p><div className="row"><label>Du<input className="input" type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Au<input className="input" type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button className="btn ghost" onClick={()=>exportCsv('comptabilite-eur.csv',[['Date','Type','Libellé','Référence','Montant EUR','Frais EUR','Paiement','Auteur'],...ledger.map(x=>[x.date,labels[x.kind],x.label,x.reference,(x.amount/100).toFixed(2),(x.fee/100).toFixed(2),x.paymentId??'',name(x.actor)])])}>Exporter la période CSV</button></div><div className="admin-summary"><div><strong>{money(income)}</strong><span>Encaissements</span></div><div><strong>{money(refund)}</strong><span>Remboursements</span></div><div><strong>{money(fees)}</strong><span>Frais PayPal</span></div><div><strong>{money(expense)}</strong><span>Dépenses</span></div><div><strong>{money(income-refund-fees-expense)}</strong><span>Solde des opérations</span></div></div></div><details className="card mt"><summary>Ajouter une dépense</summary><form className="admin-form" onSubmit={e=>submit(e,'adminExpense')}><label>Date<input className="input" name="date" type="date" required/></label><label>Libellé / fournisseur<input className="input" name="label" required/></label><label>Référence du justificatif<input className="input" name="reference" required/></label><label>Montant (€)<input className="input" type="number" min="0.01" step="0.01" name="amount" required/></label><button className="btn">Enregistrer la dépense</button></form></details><div className="card mt table-wrap"><table><thead><tr><th>Date</th><th>Type</th><th>Libellé</th><th>Montant</th><th>Frais</th><th>Référence</th></tr></thead><tbody>{[...ledger].sort((a,b)=>b.date.localeCompare(a.date)).map(x=><tr key={x.id}><td>{x.date.slice(0,10)}</td><td>{labels[x.kind]}</td><td>{x.label}</td><td>{money(x.amount)}</td><td>{money(x.fee)}</td><td>{x.reference}</td></tr>)}</tbody></table>{!ledger.length&&<p>Aucune écriture sur cette période.</p>}</div></>}
  {tab==='audit'&&<div className="card"><h2>Historique des actions administrateur</h2><p className="muted">Les 500 dernières actions. Les mots de passe ne figurent jamais dans ce journal.</p>{data.audit.map(x=><div className="admin-audit" key={x.id}><strong>{x.action}</strong><p>{new Date(x.date).toLocaleString('fr-FR')} · {name(x.actor)} · {name(x.target)}</p><p>{x.detail}</p></div>)}</div>}
  </fieldset></div>
}
