import { colorQuiz } from '../data/visualQuizzes'
import { SavedQuiz } from '../components/SavedQuiz'
import { colors, colorLesson } from '../data/colors'
import { SpeakButton } from '../components/Speak'
import { ExerciseRunner } from '../components/ExerciseRunner'
import { recordLesson, useCurrentUser } from '../lib/store'
import { Link } from 'react-router-dom'
export default function Colors() {
 const user = useCurrentUser()
 return <div className="container page"><div className="page-head"><Link className="link" to="/vocabulaire">← Vocabulaire</Link><h1>Les couleurs · 색</h1><p>Observe les 16 couleurs, écoute leur nom, puis entraîne-toi avec le QCM.</p><a className="btn" href="#color-images">Quiz visuel ↓</a> <a className="btn ghost" href="#quiz-couleurs">Passer au QCM</a></div><div className="level-grid">{colors.map(([ko,fr,hex])=><article className="card" key={ko}><div role="img" aria-label={fr} style={{height:110,background:hex,border:'1px solid #9996',borderRadius:18}}/><h2 lang="ko">{ko} <SpeakButton text={ko}/></h2><p>{fr}</p></article>)}</div><section className="card mt"><h2>Mettre une couleur dans une phrase</h2><p>색 signifie « couleur ». Ajoute le nom de la couleur devant un objet : <strong lang="ko">파란색 가방</strong> = un sac bleu.</p><p lang="ko">가방이 파란색이에요. <SpeakButton text="가방이 파란색이에요."/></p><p>가방 (sac) + 이 (sujet) + 파란색 (bleu) + 이에요 (est) → Le sac est bleu.</p><p lang="ko">무슨 색이에요? <SpeakButton text="무슨 색이에요?"/></p><p>무슨 (quel) + 색 (couleur) + 이에요? → C’est de quelle couleur ?</p><p>On rencontre aussi 빨간 사과 (une pomme rouge) et 하얀 눈 (la neige blanche). Ce sont des formes adjectivales : n’enlève pas simplement 색 à toutes les couleurs.</p></section><section className="mt" id="color-images"><h2>Reconnais la couleur</h2><SavedQuiz lesson={colorQuiz}/></section><section className="mt" id="quiz-couleurs"><h2>QCM : retrouve le nom de la couleur</h2><p>{user?'Ton résultat est sauvegardé dans ton parcours.':'Connecte-toi pour sauvegarder ton score sur tous tes appareils.'}</p><ExerciseRunner key={user?.id??'guest'} exercises={colorLesson.exercises} passMark={70} onFinish={async(score,total,_r,answers,id)=>{if(user)await recordLesson(colorLesson.id,colorLesson.title,score,total,answers,id)}}/></section></div>
}
