import { useState } from 'react'
import { Link } from 'react-router-dom'
import { workshops } from '../data/workshops'
import { qcm } from '../data/helpers'
import { ExerciseRunner } from '../components/ExerciseRunner'
import { OralPractice } from '../components/OralPractice'
import { SpeakButton } from '../components/Speak'
import { mutate, useCurrentUser, useProgress } from '../lib/store'

export default function Practice(){
 const [selected,setSelected]=useState<string|null>(null),[tab,setTab]=useState<'game'|'oral'>('game'),[run,setRun]=useState(1)
 const user=useCurrentUser(),p=useProgress()
 const workshop=workshops.find(w=>w.id===selected)
 if(workshop)return <div className="container page narrow"><button className="btn ghost small" onClick={()=>setSelected(null)}>← Toutes les situations</button><header className="scene-header" style={{backgroundImage:`linear-gradient(90deg,rgba(9,24,45,.85),rgba(9,24,45,.45)),url(${workshop.image})`}}><span className="pill">NIVEAU {workshop.levelIndex} · MISSION EN CORÉE</span><h1>{workshop.title}</h1><p>{workshop.setting}</p><div className="oral-tabs"><button className={`btn ${tab==='game'?'':'ghost'}`} onClick={()=>setTab('game')}>Jouer la scène</button><button className={`btn ${tab==='oral'?'':'ghost'}`} onClick={()=>setTab('oral')}>Prendre la parole</button></div></header>
  {tab==='game'?<><div className="card scene-intro"><h2>À toi de répondre.</h2><p>Lis la réplique de ton interlocuteur, puis choisis une réponse adaptée. Tu peux te tromper : la correction t’explique comment avancer dans la conversation.</p>{!user&&<p className="notice"><Link to="/connexion?next=/pratique">Connecte-toi</Link> pour retrouver tes missions sur tous tes appareils.</p>}</div><ExerciseRunner key={`${workshop.id}-${run}`} exercises={workshop.turns.map(t=>qcm(`${t.speaker} : « ${t.ko} » — ${t.fr}`,t.answer,t.wrong,t.explain))} seed={run} passMark={70} onFinish={async(_score,_total,_results,answers,operationId)=>{if(user)await mutate('scene',{refId:workshop.id,answers},operationId)}} onRestart={()=>setRun(v=>v+1)}/><details className="card mt"><summary>Rejouer le dialogue à voix haute</summary>{workshop.turns.map((t,i)=><div className="scene-dialogue" key={i}><p><strong>{t.speaker}</strong> <span lang="ko">{t.ko}</span> <SpeakButton text={t.ko}/></p><p className="small muted">{t.fr}</p><p><strong>Toi</strong> <span lang="ko">{t.answer}</span> <SpeakButton text={t.answer}/></p><p className="small muted">{t.translation}</p></div>)}</details><Link className="btn mt" to={`/cours/${['hangeul','debutant','elementaire','intermediaire','intermediaire-avance','avance'][workshop.levelIndex]}/${workshop.id}`}>Étudier l’atelier complet</Link></>:<OralPractice key={workshop.id} id={workshop.id} {...workshop.speech} tip={workshop.pronunciation}/>}</div>
 return <div className="container page"><div className="page-head"><p className="eyebrow">LE CORÉEN SORT DU CAHIER</p><h1>Et si tu étais à Séoul ?</h1><p className="muted">Des conversations à jouer, des idées à raconter. Essaie, écoute, recommence.</p></div><div className="scenario-grid">{workshops.map(w=>{const attempts=(p.practice??[]).filter(x=>x.refId===w.id);return <article className="scenario-card" key={w.id}><div className="scenario-photo"><img src={w.image} alt={w.image.includes('cafe')?'Une pause café à Séoul':'Séoul à la tombée de la nuit'} loading="lazy"/><span className="glass-label">NIVEAU {w.levelIndex}</span></div><div className="scenario-content"><h2>{w.title}</h2><p>{w.setting}</p><div className="row"><button className="btn" onClick={()=>{setSelected(w.id);setTab('game');setRun(1)}}>Jouer la scène ↗</button><button className="btn ghost" onClick={()=>{setSelected(w.id);setTab('oral')}}>Studio oral</button></div><p className="small muted">{attempts.length?`${attempts.length} activité${attempts.length>1?'s':''} enregistrée${attempts.length>1?'s':''}`:'4 échanges · 1 prise de parole · à ton rythme'}</p></div></article>})}</div>{(p.practice??[]).length>0&&<section className="card mt"><h2>Mes dernières missions</h2><ul className="results-list">{p.practice!.slice(0,12).map(a=><li key={a.id}><div><strong>{workshops.find(w=>w.id===a.refId)?.title??a.refId}</strong><p className="small muted">{new Date(a.date).toLocaleString('fr-FR')} · {a.kind==='scene'?`Jeu : ${a.score} / ${a.total}`:a.mode==='free'?'Discours libre':`Répétition : ${a.score} % de correspondance`}</p>{a.transcript&&<details><summary>Relire ma transcription</summary><p lang="ko">{a.transcript}</p></details>}</div></li>)}</ul></section>}</div>
}
