import { useState } from 'react'
import { Link } from 'react-router-dom'
import { levels } from '../data'
import { structureUnits } from '../data/structures'
import { useProgress } from '../lib/store'

export default function Structures(){
 const [level,setLevel]=useState('all'),[search,setSearch]=useState(''),progress=useProgress()
 const units=structureUnits.filter(u=>(level==='all'||u.level===Number(level))&&`${u.title} ${u.context} ${u.patterns.map(p=>p.form+' '+p.meaning+' '+p.rule).join(' ')}`.toLowerCase().includes(search.toLowerCase()))
 return <div className="container page"><header className="page-head"><p className="eyebrow">DU SON À LA CONVERSATION</p><h1>Comprendre et construire ses phrases</h1><p className="muted">{structureUnits.length} ateliers : phrases en contexte, décomposition, règles, nuances et exercices corrigés. Choisis une intention, puis apprends à la formuler.</p></header><div className="card"><div className="row"><label>Rechercher une structure<input className="input" placeholder="거든요, grâce à, impératif, amis…" value={search} onChange={e=>setSearch(e.target.value)}/></label><label>Niveau<select className="input" value={level} onChange={e=>setLevel(e.target.value)}><option value="all">Tous les niveaux</option>{levels.map(l=><option key={l.id} value={l.index}>{l.name}</option>)}</select></label></div><p className="small muted">Les niveaux organisent la progression pédagogique ; ils ne certifient pas un niveau TOPIK.</p></div><div className="level-grid mt">{units.map(u=><Link className="card level-card" key={u.id} to={`/cours/${levels[u.level].id}/${u.id}`}><span className="pill">{u.level===0?'Comprendre le hangeul':`Niveau ${u.level}`}</span><h2>{u.title}</h2><p>{u.context}</p><ul>{u.patterns.map(p=><li key={p.form}><strong lang="ko">{p.form}</strong> — {p.meaning}</li>)}</ul><span className="link">{progress.lessons[u.id]?.completed?'Revoir cet atelier':'Étudier les phrases'} →</span></Link>)}</div>{!units.length&&<p>Aucun atelier trouvé. Essaie un mot plus court ou un autre niveau.</p>}<section className="card mt"><h2>Et pour le TOPIK ?</h2><p>Ces ateliers consolident la langue. Une préparation à l’examen demande aussi de l’écoute, de la lecture chronométrée et, pour le TOPIK II, de la rédaction. Les exercices de ce site ne sont pas des examens officiels et terminer le parcours ne garantit pas un score.</p><a className="link" href="https://www.niied.go.kr/web/niied/contents/niied_topik" target="_blank" rel="noreferrer">Consulter la présentation officielle du TOPIK →</a><p className="small muted">Repères linguistiques : <a href="https://krdict.korean.go.kr/fra" target="_blank" rel="noreferrer">dictionnaire coréen–français de l’Institut national de la langue coréenne</a>. Exemples et exercices rédigés pour ce parcours.</p></section></div>
}
