import { Link } from 'react-router-dom'
export default function Terms() {
 return <div className="container page narrow"><article className="card prose"><h1>Conditions générales de vente</h1><p>TalkToMe Club · Version du 25 septembre 2026. Ces conditions s’appliquent aux nouvelles commandes ; elles ne modifient pas rétroactivement les achats antérieurs.</p><button className="btn ghost" onClick={()=>window.print()}>Imprimer / enregistrer en PDF</button>
 <h2>1. Prestataire et contact</h2><p>TalkToMe Club est un service exploité par <strong>Une Digitale, Naudy Alexia</strong>, entreprise individuelle suisse, titulaire Alexia Naudy. Adresse : Rue de la Plaine 3, 1400 Yverdon-les-Bains, Suisse. IDE : CHE-240.155.845. Registre du commerce du canton de Vaud : CH-550.1.187.051-0.</p><p>Questions, annulations et réclamations : <a className="link" href="mailto:alexia@skorm-agency.com">alexia@skorm-agency.com</a>.</p>
 <h2>2. Cours et ressources</h2><p>Les cours particuliers de coréen sont dispensés à distance en visioconférence. Une séance dure une heure. Le contenu est adapté au niveau et aux objectifs de l’élève : conversation, hangeul, grammaire, prononciation ou préparation au TOPIK. Aucun résultat d’examen ni délai d’apprentissage n’est garanti. Les ressources gratuites du site sont distinctes des prestations payantes. Pour un élève mineur, la commande est effectuée par son représentant légal.</p>
 <h2>3. Prix et packs</h2><ul><li>Une heure de cours particulier : 15 €.</li><li>Pack de dix heures : 100 € au total, soit 10 € par heure.</li></ul><p>Ce sont les montants totaux facturés par le prestataire, sans supplément obligatoire ajouté au paiement. Les achats sont ponctuels, sans abonnement ni renouvellement automatique. Le pack comprend dix heures au total, première séance comprise. Les heures sont utilisables sur réservation, selon les disponibilités, sans expiration contractuelle automatique. Les frais éventuels de conversion appliqués par la banque ou le prestataire de paiement du client dépendent de ses propres conditions et ne sont pas encaissés par TalkToMe Club.</p>
 <h2>4. Demande et confirmation</h2><p>L’élève choisit une formule, une date, une heure et un thème. Il peut corriger ses choix avant d’envoyer sa demande. Les créneaux sont exprimés en heure de Paris. L’enregistrement de la demande et le paiement ne confirment pas à eux seuls un créneau : le professeur doit confirmer le rendez-vous et communiquer le lien de visioconférence par e-mail. La prestation commandée, son prix et les modalités convenues sont confirmés par e-mail. Le contrat est conclu lors de l’acceptation de la commande par le prestataire. Si aucune prestation ne peut être convenue, les sommes reçues pour celle-ci sont restituées.</p>
 <h2>5. Paiement</h2><p>Le paiement est actuellement effectué sur PayPal via les liens du site. Le client vérifie la formule et le montant avant de confirmer son paiement. Il indique son e-mail de profil et, si disponible, la référence de réservation pour identifier son règlement. Le site ne collecte pas les numéros de carte. Le paiement et les crédits sont validés après vérification des fonds reçus. Airwallex n’est pas actuellement activé comme moyen d’encaissement sur le site.</p>
 <h2>6. Déroulement et report</h2><p>L’élève prévoit une connexion Internet et un appareil compatible avec la visioconférence, avec microphone. Aucun produit physique n’est expédié. Un retard de l’élève ne décale pas la fin du créneau convenu. Une demande de report ou d’annulation du créneau reçue au moins 24 heures avant le cours est gratuite : l’heure reste disponible pour une nouvelle réservation. L’annulation d’un créneau n’entraîne pas automatiquement un remboursement monétaire.</p><p>À moins de 24 heures, ou en cas d’absence de l’élève, le cours est dû et l’heure est décomptée, sous réserve des droits impératifs applicables et d’une situation exceptionnelle examinée avec le professeur. Pour une demande tardive ou un incident technique, contactez le professeur par e-mail. Si le professeur ne peut assurer le cours, l’élève peut choisir un report sans frais ou le remboursement de la partie non fournie.</p>
 <h2>7. Non-remboursement et exceptions</h2><p><strong>Les achats de cours et de packs ne sont pas remboursables à la seule initiative de l’élève, y compris en cas d’abandon ou de non-utilisation des heures.</strong> Cette règle commerciale ne supprime ni les droits légaux obligatoires, ni les recours en cas de prestation non fournie par le prestataire, ni le remboursement d’un paiement effectué en double. Lorsqu’un remboursement est dû, il porte sur la somme concernée effectivement payée ; pour le pack, une heure représente 10 €. Le traitement est effectué sans retard injustifié, dans les délais légaux applicables, par le moyen de paiement initial sauf accord contraire.</p>
 <h2>8. Rétractation et droits des consommateurs</h2><p>Le droit suisse ne prévoit pas de droit général de rétractation pour une commande en ligne. Les dispositions impératives applicables au client, notamment lorsque l’activité s’adresse aux consommateurs de l’Union européenne, restent toutefois réservées.</p><p>Lorsqu’un droit légal de rétractation de 14 jours s’applique à la prestation, ce délai court à compter de la conclusion du contrat. Le client peut notifier sa décision sans motif par e-mail ou courrier aux coordonnées indiquées à l’article 1. Un remboursement légalement dû est réalisé au plus tard dans les 14 jours suivant la notification. Pour commencer une prestation pendant ce délai, le professeur recueille préalablement la demande expresse du client. Une somme proportionnelle au service déjà fourni peut être due dans les conditions prévues par la loi. La perte du droit après exécution complète suppose les consentements et informations exigés par la loi ; la seule acceptation des présentes CGV ne vaut pas renonciation.</p><p>Modèle de notification : « À Une Digitale, Naudy Alexia, Rue de la Plaine 3, 1400 Yverdon-les-Bains, Suisse, alexia@skorm-agency.com. Je vous notifie ma rétractation du contrat portant sur [prestation], commandée le [date], référence [référence]. Nom et adresse du client : […]. Date : […]. Signature uniquement en cas d’envoi papier. »</p>
 <h2>9. Données personnelles</h2><p>Le compte permet de retrouver les réservations et la progression sur les appareils après connexion. Consultez la <Link className="link" to="/confidentialite">politique de confidentialité</Link>. Les informations de paiement sont traitées par le prestataire de paiement selon sa politique.</p>
 <h2>10. Réclamations et droit applicable</h2><p>Adressez toute réclamation à alexia@skorm-agency.com avec la référence et une description du problème pour rechercher une solution amiable. Le droit suisse s’applique sous réserve des dispositions impératives de protection du consommateur. Aucune clause ne prive le client des juridictions ou voies de recours que ces dispositions lui reconnaissent.</p></article></div>
}
