import { vocabularyLessons } from '../data/vocabularyQuizzes'
import { SavedQuiz } from '../components/SavedQuiz'
import { Link } from 'react-router-dom'
import { words, vocabularyThemes } from '../data/vocabulary'
import { useState } from 'react'
import { SpeakButton } from '../components/Speak'
export default function Vocabulary() {
 const [limit,setLimit] = useState(24)
 const [category,setCategory] = useState('Tout')
 const [query,setQuery] = useState('')
 const [hidden,setHidden] = useState(false)
 const [revealed,setRevealed] = useState<string[]>([])
 const visible = words.filter(w=>(category==='Tout'||w[0]===category)&&w.slice(1,4).join(' ').toLocaleLowerCase().includes(query.toLocaleLowerCase()))
 return <div className="container page"><div className="page-head"><h1>Le vocabulaire en photos</h1><p className="muted">132 mots répartis par thèmes, avec audio et phrases simples. Les photos de thèmes servent de repères ; les 12 cartes illustrées associent directement une photo à un mot. Cache les traductions pour tester ta mémoire.</p></div>
 <a className="btn ghost" href="#vocab-quizzes">QCM par thème ↓</a> <Link to="/couleurs" className="btn">Apprendre les couleurs →</Link><h2>Choisis ton univers</h2><div className="level-grid">{vocabularyThemes.map(t=><button key={t.name} className="card" aria-pressed={category===t.name} onClick={()=>{setCategory(t.name);setLimit(24);document.getElementById('vocab-list')?.scrollIntoView({behavior:'smooth'})}}><img src={`https://images.unsplash.com/${t.photo}?auto=format&fit=crop&w=400&q=75`} alt={`Photo du thème ${t.name}`} loading="lazy" style={{width:'100%',height:110,objectFit:'cover',borderRadius:14}}/><h3>{t.name}</h3><span>12 mots · écouter et réviser</span></button>)}</div><h2 id="vocab-list">Les mots à apprendre</h2><section className="card"><div className="row" style={{flexWrap:'wrap'}}><label>Thème <select className="input" value={category} onChange={e=>{setCategory(e.target.value);setLimit(24)}}>{['Tout',...new Set(words.map(w=>w[0]))].map(c=><option key={c}>{c}</option>)}</select></label><label>Rechercher <input className="input" value={query} onChange={e=>{setQuery(e.target.value);setLimit(24)}} placeholder="Français, coréen ou romanisation" /></label><button className="btn ghost" aria-pressed={hidden} onClick={()=>{setHidden(!hidden);setRevealed([])}}>{hidden?'Afficher les traductions':'Cacher les traductions'}</button></div></section>
 <p className="muted">{visible.length} mots · Photos : Unsplash</p><div className="level-grid">{visible.slice(0,limit).map(([cat,ko,rom,fr,sentence,translation,photo])=><article className="card" key={cat+ko}>{photo && <img src={`https://images.unsplash.com/${photo}?auto=format&fit=crop&w=640&q=80`} alt={hidden?`Illustration à reconnaître : ${cat}`:fr} loading="lazy" style={{width:'100%',height:210,objectFit:'cover',borderRadius:18}}/>}<p className="small muted">{cat}</p><h2 lang="ko">{ko} <SpeakButton text={ko}/></h2><p className="muted">{rom}</p>{!hidden||revealed.includes(ko)?<p><strong>{fr}</strong></p>:<button className="btn ghost" onClick={()=>setRevealed([...revealed,ko])}>Révéler le sens</button>}<p lang="ko">{sentence} <SpeakButton text={sentence}/></p>{(!hidden||revealed.includes(ko))&&<p>{translation}</p>}</article>)}</div>{visible.length>limit&&<button className="btn mt" onClick={()=>setLimit(limit+24)}>Voir 24 mots de plus</button>}{!visible.length&&<p>Aucun mot trouvé. Essaie un autre mot ou un autre thème.</p>}<section id="vocab-quizzes" className="mt"><h2>QCM par thème</h2><p>Chaque thème a son propre score. Choisis une série et retrouve les mots dans les deux sens.</p>{vocabularyLessons.filter(l=>category==='Tout'||l.subtitle===category).map(l=><details className="card mt" key={l.id}><summary>{l.subtitle} · {l.exercises.length} questions</summary><SavedQuiz lesson={l}/></details>)}</section></div>
}
