import { useEffect, useRef, useState } from 'react'
import { compareSpeech } from '../lib/oral'
import { speak, stopSpeaking } from '../lib/speech'
import { mutate, useCurrentUser } from '../lib/store'
import { VoiceSettings } from './VoiceSettings'
import { useCourseLang } from '../lib/courseLang'
import { useT } from '../lib/i18n'
interface Recognition {lang:string;continuous:boolean;interimResults:boolean;maxAlternatives:number;onresult:((event:any)=>void)|null;onerror:((event:any)=>void)|null;onend:(()=>void)|null;start:()=>void;stop:()=>void;abort:()=>void}
function recognitionConstructor(): (new()=>Recognition)|undefined {const w=window as unknown as {SpeechRecognition?:new()=>Recognition;webkitSpeechRecognition?:new()=>Recognition};return w.SpeechRecognition??w.webkitSpeechRecognition}
export function OralPractice({id,title,brief,model,translation,tip}:{id:string;title:string;brief:string;model:string;translation:string;tip:string}) {
 const user=useCurrentUser()
 // Autres langues : reconnaissance et voix dans la langue du cours (coréen par défaut).
 const course=useCourseLang()
 const speechLang=course?.speech??'ko-KR'
 const t=useT()
 const [mode,setMode]=useState<'repeat'|'free'>('repeat'),[transcript,setTranscript]=useState(''),[interim,setInterim]=useState(''),[listening,setListening]=useState(false),[error,setError]=useState(''),[consent,setConsent]=useState(false),[saved,setSaved]=useState(false),[saving,setSaving]=useState(false),[hasRecorded,setHasRecorded]=useState(false)
 const recognition=useRef<Recognition|null>(null),timeout=useRef<ReturnType<typeof setTimeout>|null>(null),operation=useRef(crypto.randomUUID())
 const chunks=model.match(/[^.!?]+[.!?]?/g)??[model]
 const [part,setPart]=useState(-1)
 const target=part<0?model:chunks[part].trim()
 const supported=!!recognitionConstructor()
 useEffect(()=>()=>{recognition.current?.abort();stopSpeaking();if(timeout.current)clearTimeout(timeout.current)},[])
 function reset(){recognition.current?.abort();setTranscript('');setInterim('');setError('');setSaved(false);setHasRecorded(false);operation.current=crypto.randomUUID()}
 function start(){
  const Ctor=recognitionConstructor();if(!Ctor||!consent)return
  reset();stopSpeaking();const r=new Ctor();recognition.current=r;r.lang=speechLang;r.continuous=true;r.interimResults=true;r.maxAlternatives=1
  r.onresult=e=>{let final='',pending='';for(let i=0;i<e.results.length;i++){if(e.results[i].isFinal)final+=e.results[i][0].transcript+' ';else pending+=e.results[i][0].transcript}setTranscript(final.trim());setInterim(pending);if(final.trim())setHasRecorded(true)}
  r.onerror=e=>{const messages:Record<string,string>={'not-allowed':t('Microphone refusé. Autorise le micro pour ce site dans ton navigateur, puis réessaie.','Microphone blocked. Allow the microphone for this site in your browser, then try again.'),'audio-capture':t('Aucun microphone disponible. Vérifie ton casque ou ton téléphone.','No microphone available. Check your headset or phone.'),'network':t('La transcription nécessite une connexion. Vérifie le réseau et réessaie.','Transcription needs a connection. Check the network and try again.'),'no-speech':t('Aucune parole détectée. Rapproche-toi du micro et réessaie.','No speech detected. Move closer to the microphone and try again.'),'language-not-supported':t('La reconnaissance de cette langue n’est pas disponible sur ce navigateur.','Speech recognition for this language is not available in this browser.')};setError(messages[e.error]??t('La reconnaissance a été interrompue. Tu peux réessayer.','Recognition was interrupted. You can try again.'));setListening(false)}
  r.onend=()=>{setListening(false);setInterim('');if(timeout.current)clearTimeout(timeout.current)}
  try{r.start();setListening(true);timeout.current=setTimeout(()=>r.stop(),120000)}catch{setError(t('Impossible de démarrer le microphone. Ferme les autres enregistrements et réessaie.','Could not start the microphone. Close other recordings and try again.'))}
 }
 const comparison=transcript&&mode==='repeat'?compareSpeech(target,transcript):null
 async function save(){if(!hasRecorded||!transcript)return;setSaving(true);setError('');try{await mutate('oral',{refId:id,mode,part,transcript},operation.current);setSaved(true)}catch(e){setError((e as Error).message)}finally{setSaving(false)}}
 return <section className="card oral-practice"><div className="row between"><span className="pill">{t('STUDIO ORAL','SPEAKING STUDIO')}</span><span className="small muted">Micro · {course?(t('fr','en')==='en'?({'ja-JP':'Japanese','es-ES':'Spanish','en-GB':'English','fr-FR':'French'} as Record<string,string>):({'ja-JP':'japonais','es-ES':'espagnol','en-GB':'anglais','fr-FR':'français'} as Record<string,string>))[course.speech]??course.speech:t('coréen','Korean')}</span></div><h2>{title}</h2><p>{brief}</p>
  <div className="oral-tabs" role="group" aria-label={t('Mode d’exercice','Exercise mode')}><button className={`btn ${mode==='repeat'?'':'ghost'}`} onClick={()=>{reset();setMode('repeat')}}>{t('Répéter le modèle','Repeat the model')}</button><button className={`btn ${mode==='free'?'':'ghost'}`} onClick={()=>{reset();setMode('free')}}>{t('Mon discours libre','My free talk')}</button></div>
  <div className="oral-model"><h3>{mode==='repeat'?t('Écoute, puis à toi.','Listen, then your turn.'):t('Un exemple pour préparer tes idées','An example to prepare your ideas')}</h3>{mode==='repeat'&&<label>{t('Passage à travailler','Part to practise')}<select className="input" value={part} onChange={e=>{reset();setPart(Number(e.target.value))}}><option value={-1}>{t('Le modèle complet','The full model')}</option>{chunks.map((c,i)=><option key={i} value={i}>{t('Phrase','Sentence')} {i+1} · {c.trim().slice(0,36)}</option>)}</select></label>}<p className={course?'':'ko-text'} lang={speechLang}>{mode==='repeat'?target:model}</p><details><summary>{t('Voir la traduction','See the translation')}</summary><p>{translation}</p></details><div className="row"><button className="btn ghost small" onClick={()=>speak(mode==='repeat'?target:model,{rate:.9,lang:speechLang,onError:setError})}>{t('Écouter le modèle','Listen to the model')}</button><button className="btn ghost small" onClick={()=>speak(mode==='repeat'?target:model,{rate:.65,lang:speechLang,onError:setError})}>{t('Écouter lentement','Listen slowly')}</button></div></div>
  {!course&&<VoiceSettings />}
  {supported?<><label className="mic-consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} disabled={listening}/> {t('J’accepte d’activer le micro. Mon navigateur peut transmettre ma voix à son service de reconnaissance. Le site conserve seulement la transcription si je l’enregistre.','I agree to turn on the microphone. My browser may send my voice to its recognition service. The site only keeps the transcript if I save it.')}</label><div className="row"><button className={`btn mic-button ${listening?'listening':''}`} disabled={!consent||saving} onClick={()=>listening?recognition.current?.stop():start()}>{listening?t('■ Terminer ma prise de parole','■ Finish speaking'):t('● À moi de parler','● My turn to speak')}</button><span className="small muted">{listening?t('Je t’écoute… (2 min maximum)','I’m listening… (2 min max)'):t('Écoute d’abord le modèle au casque pour éviter l’écho.','Listen to the model with headphones first to avoid echo.')}</span></div></>:<p className="notice">{t('La transcription vocale n’est pas disponible sur ce navigateur. Essaie Chrome sur ordinateur ou Android. Tu peux toujours écouter, répéter et travailler ton discours avec le modèle.','Voice transcription is not available in this browser. Try Chrome on a computer or Android. You can still listen, repeat and work on your talk with the model.')}</p>}
  {error&&<p className="error" role="alert">{error}</p>}
  <div className="transcript-box" aria-live="polite"><span className="eyebrow">{t('CE QUE LE MICRO A COMPRIS','WHAT THE MICROPHONE HEARD')}</span><p lang={speechLang} className={course?'':'ko-text'}>{transcript||interim||t('Ta transcription apparaîtra ici.','Your transcript will appear here.')} {transcript&&<span className="muted">{interim}</span>}</p></div>
  {!listening&&comparison&&<div className={`oral-feedback ${comparison.similarity>=85?'ok':'review'}`}><h3>{comparison.similarity>=85?t('Les mots sont bien reconnus !','The words were recognised!'):t('Quelques passages sont à reprendre.','A few parts need another go.')}</h3><p><strong>{comparison.similarity} % {t('de correspondance textuelle','text match')}</strong> {t('avec le modèle.','with the model.')}</p><p className="small">{t('Ce score compare les mots transcrits : ce n’est pas une note phonétique. Le bruit ou le microphone peuvent aussi changer le résultat.','This score compares the transcribed words: it is not a phonetic mark. Noise or the microphone can also change the result.')}</p>{comparison.missing.length>0&&<><p>{t('À réécouter et répéter :','Listen again and repeat:')}</p><div className="row">{comparison.missing.map((word,i)=><button key={i} className="chip" lang={speechLang} onClick={()=>speak(word,{rate:.65,lang:speechLang,onError:setError})}>{word} ♫</button>)}</div></>}{comparison.extra.length>0&&<p className="small">{t('Transcrit différemment','Transcribed differently')} : {comparison.extra.join(' · ')}</p>}<p className="oral-tip">{tip}</p><button className="btn ghost" onClick={()=>speak(target,{rate:.65,lang:speechLang,onError:setError})}>{t('Réécouter la phrase corrigée','Listen to the correct sentence again')}</button></div>}
  {!listening&&transcript&&mode==='free'&&<div className="oral-feedback"><h3>{t('Ton discours est transcrit.','Your talk has been transcribed.')}</h3><p>{t('Relis-le : as-tu présenté le sujet, donné un exemple et terminé ton idée ? Compare ta structure au modèle. Un discours libre peut être correct avec d’autres mots ; aucune note automatique de prononciation ou de grammaire n’est attribuée.','Read it again: did you introduce the topic, give an example and finish your idea? Compare your structure with the model. A free talk can be correct with other words; no automatic mark for pronunciation or grammar is given.')}</p><p className="oral-tip">{tip}</p></div>}
  {!listening&&hasRecorded&&transcript&&<div className="row mt"><button className="btn" disabled={!user||saved||saving} onClick={save}>{saving?t('Enregistrement…','Saving…'):saved?t('Enregistré dans mon parcours ✓','Saved to my progress ✓'):user?t('Garder cette prise de parole','Keep this recording'):t('Connecte-toi pour sauvegarder','Log in to save')}</button><button className="btn ghost" onClick={reset}>{t('Effacer et recommencer','Clear and start again')}</button></div>}
 </section>
}
