import { useEffect, useRef, useState } from 'react'
import { compareSpeech } from '../lib/oral'
import { speak, stopSpeaking } from '../lib/speech'
import { mutate, useCurrentUser } from '../lib/store'
import { VoiceSettings } from './VoiceSettings'
interface Recognition {lang:string;continuous:boolean;interimResults:boolean;maxAlternatives:number;onresult:((event:any)=>void)|null;onerror:((event:any)=>void)|null;onend:(()=>void)|null;start:()=>void;stop:()=>void;abort:()=>void}
function recognitionConstructor(): (new()=>Recognition)|undefined {const w=window as unknown as {SpeechRecognition?:new()=>Recognition;webkitSpeechRecognition?:new()=>Recognition};return w.SpeechRecognition??w.webkitSpeechRecognition}
export function OralPractice({id,title,brief,model,translation,tip}:{id:string;title:string;brief:string;model:string;translation:string;tip:string}) {
 const user=useCurrentUser()
 const [mode,setMode]=useState<'repeat'|'free'>('repeat'),[transcript,setTranscript]=useState(''),[interim,setInterim]=useState(''),[listening,setListening]=useState(false),[error,setError]=useState(''),[consent,setConsent]=useState(false),[saved,setSaved]=useState(false),[saving,setSaving]=useState(false),[hasRecorded,setHasRecorded]=useState(false)
 const recognition=useRef<Recognition|null>(null),timeout=useRef<ReturnType<typeof setTimeout>|null>(null),operation=useRef(crypto.randomUUID())
 const chunks=model.match(/[^.!?]+[.!?]?/g)??[model]
 const [part,setPart]=useState(-1)
 const target=part<0?model:chunks[part].trim()
 const supported=!!recognitionConstructor()
 useEffect(()=>()=>{recognition.current?.abort();stopSpeaking();if(timeout.current)clearTimeout(timeout.current)},[])
 function reset(){recognition.current?.abort();setTranscript('');setInterim('');setError('');setSaved(false);setHasRecorded(false);operation.current=crypto.randomUUID()}
 function start(){
  const Ctor=recognitionConstructor();if(!Ctor||!consent)return
  reset();stopSpeaking();const r=new Ctor();recognition.current=r;r.lang='ko-KR';r.continuous=true;r.interimResults=true;r.maxAlternatives=1
  r.onresult=e=>{let final='',pending='';for(let i=0;i<e.results.length;i++){if(e.results[i].isFinal)final+=e.results[i][0].transcript+' ';else pending+=e.results[i][0].transcript}setTranscript(final.trim());setInterim(pending);if(final.trim())setHasRecorded(true)}
  r.onerror=e=>{const messages:Record<string,string>={'not-allowed':'Microphone refusé. Autorise le micro pour ce site dans ton navigateur, puis réessaie.','audio-capture':'Aucun microphone disponible. Vérifie ton casque ou ton téléphone.','network':'La transcription nécessite une connexion. Vérifie le réseau et réessaie.','no-speech':'Aucune parole détectée. Rapproche-toi du micro et réessaie.','language-not-supported':'La reconnaissance du coréen n’est pas disponible sur ce navigateur.'};setError(messages[e.error]??'La reconnaissance a été interrompue. Tu peux réessayer.');setListening(false)}
  r.onend=()=>{setListening(false);setInterim('');if(timeout.current)clearTimeout(timeout.current)}
  try{r.start();setListening(true);timeout.current=setTimeout(()=>r.stop(),120000)}catch{setError('Impossible de démarrer le microphone. Ferme les autres enregistrements et réessaie.')}
 }
 const comparison=transcript&&mode==='repeat'?compareSpeech(target,transcript):null
 async function save(){if(!hasRecorded||!transcript)return;setSaving(true);setError('');try{await mutate('oral',{refId:id,mode,part,transcript},operation.current);setSaved(true)}catch(e){setError((e as Error).message)}finally{setSaving(false)}}
 return <section className="card oral-practice"><div className="row between"><span className="pill">STUDIO ORAL</span><span className="small muted">Micro · coréen</span></div><h2>{title}</h2><p>{brief}</p>
  <div className="oral-tabs" role="group" aria-label="Mode d’exercice"><button className={`btn ${mode==='repeat'?'':'ghost'}`} onClick={()=>{reset();setMode('repeat')}}>Répéter le modèle</button><button className={`btn ${mode==='free'?'':'ghost'}`} onClick={()=>{reset();setMode('free')}}>Mon discours libre</button></div>
  <div className="oral-model"><h3>{mode==='repeat'?'Écoute, puis à toi.':'Un exemple pour préparer tes idées'}</h3>{mode==='repeat'&&<label>Passage à travailler<select className="input" value={part} onChange={e=>{reset();setPart(Number(e.target.value))}}><option value={-1}>Le modèle complet</option>{chunks.map((c,i)=><option key={i} value={i}>Phrase {i+1} · {c.trim().slice(0,36)}</option>)}</select></label>}<p className="ko-text" lang="ko">{mode==='repeat'?target:model}</p><details><summary>Voir la traduction</summary><p>{translation}</p></details><div className="row"><button className="btn ghost small" onClick={()=>speak(mode==='repeat'?target:model,{rate:.9,onError:setError})}>Écouter le modèle</button><button className="btn ghost small" onClick={()=>speak(mode==='repeat'?target:model,{rate:.65,onError:setError})}>Écouter lentement</button></div></div>
  <VoiceSettings />
  {supported?<><label className="mic-consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} disabled={listening}/> J’accepte d’activer le micro. Mon navigateur peut transmettre ma voix à son service de reconnaissance. Le site conserve seulement la transcription si je l’enregistre.</label><div className="row"><button className={`btn mic-button ${listening?'listening':''}`} disabled={!consent||saving} onClick={()=>listening?recognition.current?.stop():start()}>{listening?'■ Terminer ma prise de parole':'● À moi de parler'}</button><span className="small muted">{listening?'Je t’écoute… (2 min maximum)':'Écoute d’abord le modèle au casque pour éviter l’écho.'}</span></div></>:<p className="notice">La transcription vocale n’est pas disponible sur ce navigateur. Essaie Chrome sur ordinateur ou Android. Tu peux toujours écouter, répéter et travailler ton discours avec le modèle.</p>}
  {error&&<p className="error" role="alert">{error}</p>}
  <div className="transcript-box" aria-live="polite"><span className="eyebrow">CE QUE LE MICRO A COMPRIS</span><p lang="ko" className="ko-text">{transcript||interim||'Ta transcription apparaîtra ici.'} {transcript&&<span className="muted">{interim}</span>}</p></div>
  {!listening&&comparison&&<div className={`oral-feedback ${comparison.similarity>=85?'ok':'review'}`}><h3>{comparison.similarity>=85?'Les mots sont bien reconnus !':'Quelques passages sont à reprendre.'}</h3><p><strong>{comparison.similarity} % de correspondance textuelle</strong> avec le modèle.</p><p className="small">Ce score compare les mots transcrits : ce n’est pas une note phonétique. Le bruit ou le microphone peuvent aussi changer le résultat.</p>{comparison.missing.length>0&&<><p>À réécouter et répéter :</p><div className="row">{comparison.missing.map((word,i)=><button key={i} className="chip" lang="ko" onClick={()=>speak(word,{rate:.65,onError:setError})}>{word} ♫</button>)}</div></>}{comparison.extra.length>0&&<p className="small">Transcrit différemment : {comparison.extra.join(' · ')}</p>}<p className="oral-tip">{tip}</p><button className="btn ghost" onClick={()=>speak(target,{rate:.65,onError:setError})}>Réécouter la phrase corrigée</button></div>}
  {!listening&&transcript&&mode==='free'&&<div className="oral-feedback"><h3>Ton discours est transcrit.</h3><p>Relis-le : as-tu présenté le sujet, donné un exemple et terminé ton idée ? Compare ta structure au modèle. Un discours libre peut être correct avec d’autres mots ; aucune note automatique de prononciation ou de grammaire n’est attribuée.</p><p className="oral-tip">{tip}</p></div>}
  {!listening&&hasRecorded&&transcript&&<div className="row mt"><button className="btn" disabled={!user||saved||saving} onClick={save}>{saving?'Enregistrement…':saved?'Enregistré dans mon parcours ✓':user?'Garder cette prise de parole':'Connecte-toi pour sauvegarder'}</button><button className="btn ghost" onClick={reset}>Effacer et recommencer</button></div>}
 </section>
}
